server:
  port: 5000
#  servlet:
#    context-path: /test


spring:
  datasource:
    url: "jdbc:mysql://26.168.186.68:3306/oneshop"
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false