server:
  port: 5000
#  servlet:
#    context-path: /test


spring:
  datasource:
<<<<<<< HEAD
    url: "jdbc:mysql://127.0.0.1:3306/oneshop"
    username: root
    password: 1234
=======
    url: "jdbc:mysql://26.168.186.68:3306/oneshop"
    username: username
    password: password
>>>>>>> remotes/origin/mun
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false